name: Keep Render Alive

on:
  schedule:
    - cron: "*/122220 * * * *"   # Ejecuta cada 20 minutos
  workflow_dispatch:        # Permite correrlo manualmente desde Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: curl -s https://academia-torneos.onrender.com/ > /dev/null
